### ISSUE TITLE
big picture

### ISSUE THREAD

**Issue by devsnek** [reundefined/discord.htc#3]
Soooooo...

an event named "createdMessage", a method named "makeMessage" and then there's the whole "snip" deal.

I think you should deal with this asap. Predictability is super important, and you guys seem to have been ignoring it for the most part.

**Comment by nekonez** [comment]
i CAN change the method names but that would be a big change that can break numerous bots that currently use the library.

**Comment by GusCaplan** [comment]
this is why major versions exist (see: discord.js v8 vs v9)

**Comment by AbsoluteZero273** [comment]
I think question label does not fit here
